Add doesntExist to passthru
jenssegers/laravel-mongodb pull request #2194
Opened 2021-02-02 21:54 UTC by simonschaufi

Those calls should return the same result but instead the call to "doesntExist" returns an object.

```php
!$user->groups()->exists();
$user->groups()->doesntExist();
```

2021-02-02 23:50 UTC, divine requested changes
Hello,

There are other missing passthru functions. See https://github.com/jenssegers/laravel-mongodb/issues/1765

Could you please kindly add missing ones from https://github.com/illuminate/database/blob/8.x/Eloquent/Builder.php#L81-L84 to make it consistent?

I have prepared my own PR for this a few months back but it was delayed as we didn't decide how to test this at all between versions.

Thanks!

2021-02-23 04:11 UTC, divine commented
Hello @simonschaufi,

Do you plan to complete this PR or should I close and push on my own?

Thanks!

2021-02-23 23:10 UTC, simonschaufi commented
@divine you can make adjustments on my branch actually. I'm traveling at the moment and could finish it in march

2021-04-29 18:42 UTC, divine submitted a review, later dismissed

2021-04-29 19:25 UTC, simonschaufi commented
@divine Thanx! Is there anything still to do for me or will you merge it?

2021-04-29 19:52 UTC, divine commented
> @divine Thanx! Is there anything still to do for me or will you merge it?

Hello @simonschaufi ,

We will merge it tomorrow, just waiting for @Smolevich review just in case.

The last push was to fix the link of related PR and nothing is left.

Thanks!

2021-04-29 19:52 UTC, divine approved these changes

2021-04-29 19:55 UTC, simonschaufi commented
Awesom!

2021-04-30 07:19 UTC, Smolevich approved these changes

2021-04-30 07:21 UTC, merged

2021-04-30 08:06 UTC, simonschaufi commented
@divine @Smolevich can this also be backported into older releases? that would be great!

2021-04-30 08:09 UTC, divine commented
> @divine @Smolevich can this also be backported into older releases? that would be great!

If you can take care of it, why not 😁.

Thanks!

2021-04-30 08:11 UTC, divine commented
Anyways, I might take care of it at the weekend if you're busy @simonschaufi .

Thanks!