fix(2228): added transaction free deleteAndRelease() Method
jenssegers/laravel-mongodb pull request #2229
Opened 2021-04-06 18:04 UTC by sodoardi

2021-04-06 19:01 UTC, divine commented
Duplicate https://github.com/jenssegers/laravel-mongodb/pull/2180

2021-04-07 06:41 UTC, sodoardi commented
Wow.. didn't see that, looked everywhere to find a solution 🤦‍♂️
How can we get one of the fixes published? Looks like the other fix is stuck since 3 months now

2021-04-21 10:28 UTC, alliuqemal approved these changes

2021-04-21 13:38 UTC, sodoardi commented
@divine any updates on how best to proceed? Close this PR and wait for the other one to be released or how do we plan on getting this bug fixed?

2021-04-21 13:43 UTC, divine commented
> @divine any updates on how best to proceed? Close this PR and wait for the other one to be released or how do we plan on getting this bug fixed?

Hello,

I will talk with @Smolevich today and let you know what we've decided.

Thanks!

2021-04-22 08:02 UTC, Smolevich approved these changes

2021-04-22 08:06 UTC, Smolevich requested changes

2021-04-22 08:06 UTC, Smolevich commented on tests/QueueTest.php
> +        $this->assertEquals(1, $jobs[0]['attempts']);
Add additional assert like [here](https://github.com/jenssegers/laravel-mongodb/pull/2180/files), please

2021-04-29 07:27 UTC, sodoardi commented
I'll take a look this weekend

2021-05-01 17:01 UTC, divine commented
> I'll take a look this weekend

Any update?

Thanks!

2021-05-02 06:43 UTC, sodoardi commented
> > I'll take a look this weekend
> 
> Any update?
> 
> Thanks!

@divine at least give me the whole weekend 😁
@Smolevich I added a test calling directly to the Queue::deleteAndRelease() method, I hope thats how you meant it!

2021-05-02 06:57 UTC, divine commented
> @divine at least grant me the whole weekend 😁

Sorry but this is an open-source, contributors vanishing sometimes without any reply... and it was urgent for you too so no waiting whole weekend 🤣 

> @Smolevich I added a test calling directly to the Queue::deleteAndRelease() method, I hope thats how you meant it!

I think he meant this part:

```php
$this->assertEquals(0, $result['reserved']);
$this->assertNull($result['reserved_at']);
$this->assertEquals(
        Carbon::now()->addRealSeconds($delay)->getTimestamp(),
        $result['available_at']
);
$this->assertEquals(Carbon::now()->getTimestamp(), $result['created_at']);
$this->assertEquals($job->getRawBody(), $result['payload']);
```

Thanks!

2021-05-02 07:44 UTC, sodoardi commented
@divine  oh no, I hope nothing bad happens to them. Should I be worried about my safety? 🤣
I did some restructuring on the tests, hope that works out! I won't be able to check back until this evening though (european time)

2021-05-02 07:50 UTC, Smolevich commented
Resolve merge conflicts, please

2021-05-02 07:51 UTC, Smolevich requested changes
Needs work

2021-05-02 08:02 UTC, divine approved these changes

2021-05-02 08:31 UTC, divine commented
> @divine oh no, I hope nothing bad happens to them. Should I be worried about my safety? 🤣
> I did some restructuring on the tests, hope that works out! I won't be able to check back until this evening though (european time)

Don't worry about your safety, we're just having a fun conversation, so I ruined fun now completely 😄.

I really don't know what happens with them, probably too busy and it just works 😮.

Anyways, thank you for your contribution!

2021-05-02 08:37 UTC, merged