Fix/stringable sort
jenssegers/laravel-mongodb pull request #2420
Opened 2022-07-16 09:59 UTC by apeisa

This PR replaces an [older one](https://github.com/jenssegers/laravel-mongodb/pull/2419). This is a safe fix, where we type cast column value to `string` when ordering. This is more inline in how Eloquent method we overwrite works too.

There are simple tests to show how now you can now pass objects that implement `Stringable` as a `$column` variable for `orderBy` method.

I wasn't sure where to add that mockable class, so I did put it directly into QueryTest.php file.

2022-07-16 10:04 UTC, apeisa commented
You can also see all tests passing from my own workflows here https://github.com/apeisa/laravel-mongodb/actions/runs/2681478769

2022-07-23 06:19 UTC, apeisa commented
@divine Is it possible to merge this?

2022-07-23 06:29 UTC, divine requested changes
Also, point me where exactly that library converts this to the stringable object.

Thanks!

2022-07-23 06:29 UTC, divine commented on tests/QueryTest.php
> +        $age = new stringableObject('age');
```suggestion
        $age = str('age');
```

See @ https://laravel.com/docs/9.x/helpers#method-str

2022-07-23 06:29 UTC, divine commented on tests/QueryTest.php
> +}
```suggestion
```

2022-07-25 11:23 UTC, apeisa commented
Thanks for the suggestion, didn't know about the `str()` helper, makes the test much cleaner!

Not sure I understand your request:

> Also, point me where exactly that library converts this to the stringable object.

If you are referring to the Filament library - I don't think it matters (this fix is not about Filament only). I mean the Eloquent [orderBy](https://github.com/laravel/framework/blob/ac56c4f9a388855eb6bce4c0ba04ba8d559d3064/src/Illuminate/Database/Query/Builder.php#L2201-L2232) method that we are overriding allows multiple objects (in addition to string). Most of them are Queryable-objects, but it also accepts Illuminate\Database\Query\Expression -objects, which are stringable ones.

So we could use also `$age = new \Illuminate\Database\Query\Expression('age');` where we now have `str('age');` to make that point more clear.

So this fix simply make it possible to give any stringable object for `orderBy` method, instead of pure string. Of course, we could check also if the object is `Expression`, only then we do type cast to string, but I think this code is cleaner and more future-proof this way.

2022-07-26 05:36 UTC, divine approved these changes

2022-09-01 07:31 UTC, apeisa commented
@divine @Smolevich any hope to get this merged for the next release?

2022-09-01 09:09 UTC, Smolevich approved these changes

2022-09-01 09:58 UTC, merged

2022-09-01 15:00 UTC, apeisa commented
Thanks!