PHPORM-151 Update signature of `Query\Builder::dump` to match parent `DumpableTrait`
jenssegers/laravel-mongodb pull request #2730
Opened 2024-02-20 14:03 UTC by GromNaN

Fix [PHPORM-151](https://jira.mongodb.org/browse/PHPORM-151)

Laravel 11 breaking change: https://github.com/laravel/framework/commit/4326fc350de2d9e5b1578a0122a8c428895e8391#diff-2ed94a0ea151404a12f3c0d52ae9fb5742348578ec4a8ff79d079fa598ff145dR3878

### Checklist

- [x] Add tests and ensure they pass (no tests)
- [x] Add an entry to the CHANGELOG.md file
- [x] Update documentation for new features (no doc)

2024-02-20 14:03 UTC, alcaeus approved these changes

2024-02-20 14:04 UTC, alcaeus requested changes
Pull request should target 5.0 if we consider this a breaking change, or 4.2 if we don't.

2024-02-20 14:08 UTC, GromNaN commented
> Pull request should target 5.0 if we consider this a breaking change, or 4.2 if we don't.

I added this method last week #2727, it's not released yet.

2024-02-21 10:20 UTC, alcaeus approved these changes
Discussed offline. Adding `dump` in 4.1 is a bugfix, and it makes sense to make the signature compatible with Laravel 11 while we're adding it. LGTM!

2024-02-21 10:21 UTC, merged