DOCSP-41241: Laravel Sanctum
jenssegers/laravel-mongodb pull request #3050
Opened 2024-07-16 18:01 UTC by norareidy

### Checklist

- [ ] Add tests and ensure they pass
- [ ] Add an entry to the CHANGELOG.md file
- [ ] Update documentation for new features

2024-07-17 13:35 UTC, GromNaN requested changes
I would say in the introduction that Laravel Sanctum work by overriding the default model with a model that brings MongoDB features. Everything else works the same.

2024-07-17 13:35 UTC, GromNaN commented on docs/user-authentication.txt
> +   php artisan migrate
This last command cannot be done before the model is updated to use the `DocumentModel` trait.

2024-07-17 13:35 UTC, GromNaN commented on docs/user-authentication.txt
> +Example
This is not an example but the required procedure.

2024-07-17 15:22 UTC, rustagir requested changes
a couple of suggestions about flow

2024-07-17 15:22 UTC, rustagir commented on docs/user-authentication.txt
> +In this section, you can learn how to use the following features to
S: before this sentence, add a sentence explaining why someone might want to make a custom model

2024-07-17 15:22 UTC, rustagir commented on docs/user-authentication.txt
> +You can install the Laravel Sanctum package to provide API tokens to users
S: add a sentence explaining broadly what laravel sanctum is

2024-07-17 15:22 UTC, rustagir commented on docs/user-authentication.txt
> +each token in a database table and authenticates incoming HTTP requests through
```suggestion
each token in a database table and authenticates incoming HTTP requests by using
```

2024-07-17 15:22 UTC, rustagir commented on docs/user-authentication.txt
> +   section of the Laravel Sanctum guide.
```suggestion
   To learn more about installing and configuring Laravel Sanctum, see
   `Installation <https://laravel.com/docs/{+laravel-docs-version+}/sanctum#installation>`__
   in the Laravel Sanctum guide.
```

2024-07-17 15:22 UTC, rustagir commented on docs/user-authentication.txt
> +model provided by Sanctum.
S: provide a little more explanation of what is required here

2024-07-17 19:39 UTC, rustagir approved these changes
lgtm

2024-07-17 22:04 UTC, GromNaN commented on docs/user-authentication.txt
> +API tokens that are stored in a database table and authenticates incoming HTTP
Are you sure to keep the word "table", it refers to the SQL database.
```suggestion
API tokens that are stored in the database and authenticates incoming HTTP
```

2024-07-19 17:27 UTC, GromNaN approved these changes
SGTM

2024-07-19 17:33 UTC, merged